from typing import List, Literal

from pydantic import BaseModel, Field


class MainAnswer(BaseModel):
    answer: str = Field(description="Main answer generated by Gemini")
    caveats: List[str] = Field(default_factory=list)


class AuditResult(BaseModel):
    risk_level: Literal["Safe", "Needs Review", "High Risk"]
    risk_score: int = Field(ge=0, le=100)
    short_verdict: str
    issues_found: List[str] = Field(default_factory=list)
    missing_points: List[str] = Field(default_factory=list)
    overconfident_phrases: List[str] = Field(default_factory=list)
    safer_rewrite: str
    explanation: str


class WorkflowResult(BaseModel):
    prompt: str
    generated_answer: MainAnswer
    audit: AuditResult
    rule_hits: List[str] = Field(default_factory=list)
    final_score: int = Field(ge=0, le=100)
    final_level: Literal["Safe", "Needs Review", "High Risk"]